# Generated by Django 3.0.5 on 2020-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200)),
                ('subscriptions', models.DecimalField(decimal_places=1, max_digits=10000000)),
                ('videos', models.DecimalField(decimal_places=1, max_digits=1000000)),
                ('views', models.DecimalField(decimal_places=1, max_digits=10000000)),
            ],
        ),
    ]
